### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by ferponcem** [individual-brain-charting/docs#1]
## About this list

This list gathers what we are planning on doing next for the IBC web-based documentation.

## ToDo:

- [x] Include response devices
- [x] Include audio devices for early sessions (optoacoustics) (Fer)
- [x] Complete the *all_contrasts* file `pretty_name` field (Fer)
- [ ] Create the rest of the videos
- [ ] Include youtube links
- [ ] Specify the type of commits that trigger *actions*
- [x] Modify the `Get the data` section: use some descriptions and embed the links 
- [x] Use siibra to retrive the data (in the meantime) in a notebook 
- [ ] Manage color code for cognitve tags
- [ ] Update the `Organization of the MRI sessions` figure
- [ ] Fill the `Acquisition table` section
- [ ] Add short explanation on why the movie tasks don't have conditions/contrasts
- [ ] Sort out building references.rst page automatically, if needed
